services:
  api:
    build: .  # Constr칩i a imagem a partir do Dockerfile na pasta atual ('.')
    container_name: recsys_api
    ports:
      # Mapeia a porta 8000 da m치quina (host) 
      # para a porta 8000 do container (app)
      - "8000:8000"
    env_file:
      # Carrega todas as vari치veis do arquivo .env 
      # como vari치veis de ambiente dentro do container
      - .env
    volumes:
      - ./app:/app/app